# Generated by Django 5.1.6 on 2025-04-05 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=200)),
                ('productDescription', models.TextField()),
                ('productPicture', models.URLField()),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productCategory', models.CharField(choices=[('Camisetas', 'Camisetas'), ('Pantalones', 'Pantalones'), ('Zapatos', 'Zapatos'), ('Chaquetas', 'Chaquetas'), ('Accesorios', 'Accesorios'), ('Otros', 'Otros')], max_length=100)),
                ('productBrand', models.CharField(max_length=100)),
                ('productStock', models.PositiveIntegerField(default=10)),
                ('productBuyLink', models.URLField()),
                ('productLink', models.URLField(unique=True)),
                ('productOrigin', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
