# Generated by Django 5.1.6 on 2025-05-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productLink',
            field=models.URLField(),
        ),
    ]
